/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type LoanRequest = ContractEventLog<{
  alexWallet: string;
  asset: string;
  status: string;
  contractId: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface AssetSide extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): AssetSide;
  clone(): AssetSide;
  methods: {
    acceptLoan(
      _contractId: string | number[],
      _preImage1: string | number[]
    ): NonPayableTransactionObject<void>;

    askForLoan(
      _asset: string,
      _tokenId: number | string | BN,
      _assetOwner: string,
      _secret1Hash: string | number[],
      _reqTill: number | string | BN,
      _acceptTill: number | string | BN,
      _lockedTill: number | string | BN,
      _releaseTill: number | string | BN
    ): NonPayableTransactionObject<void>;

    getContract1(_contractId: string | number[]): NonPayableTransactionObject<{
      secret1Hash: string;
      secret2Hash: string;
      preimage1: string;
      preimage2: string;
      assetContract: string;
      tokenId: string;
      loanAmount: string;
      loanInterest: string;
      lenderDeposit: string;
      bobsWalet: string;
      alexWallet: string;
      status: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: string;
      8: string;
      9: string;
      10: string;
      11: string;
    }>;

    getContract2(_contractId: string | number[]): NonPayableTransactionObject<{
      reqTill: string;
      acceptTill: string;
      lockedTill: string;
      releaseTill: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    giveLoan(
      _contractId: string | number[],
      _secret2Hash: string | number[]
    ): NonPayableTransactionObject<void>;

    loanDefault(
      _contractId: string | number[],
      _preImage2: string | number[]
    ): NonPayableTransactionObject<boolean>;

    noTakersForLoan(): NonPayableTransactionObject<void>;

    owner(): NonPayableTransactionObject<string>;

    releaseCollatoral(
      _contractId: string | number[],
      _preImage2: string | number[]
    ): NonPayableTransactionObject<void>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;
  };
  events: {
    LoanRequest(cb?: Callback<LoanRequest>): EventEmitter;
    LoanRequest(
      options?: EventOptions,
      cb?: Callback<LoanRequest>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "LoanRequest", cb: Callback<LoanRequest>): void;
  once(
    event: "LoanRequest",
    options: EventOptions,
    cb: Callback<LoanRequest>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
